#selected df 600 sec to 900 sec to represent meditation phase and change to 120 and 360 to represente the story phase
#rule of nomination (story phase for example)
#pairs: correlation between 2 biomarks
#pairs_betweenBioMAndFP1ThetaStory.pdf consists of conventional biomarks and fp1theta
#pairs_HRV(electrode name)Story.pdf consists HRV and 4 wave band in one eletrode
#pairs_(wave band)(brain area)Story.pdf consists of this wave band off qll the electrodes in this brain area
#(signal name)againsttime.pdf consists of this signal duiring the whole experience
#df=a matrix generated by df_generation
#subject_name exemple = "HU"
#if f is obtained by read.csv()
#must change to factor
#df$MediOrStory<-factor(ifelse(df$MediOrStory%in%c('0'),'0','1'))
#the function will return a pvalue table

#go to the en to change path where you want to store the p-value table

graph_generation=function(df,subject_name){
  
  dfslted=df[which(df[,'time']>120),]
  dfslted=dfslted[which(dfslted[,'time']<360),]

  pdf(file = "pairs_betweenBioMAndFP1ThetaStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HR", "SC", "HRV", "Resp","ST","FP1ThetaMean")])
  dev.off()
  pdf(file = "pairs_HRVFP1Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FP1ThetaMean","FP1AlphaMean","FP1BetaMean","FP1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVFP2Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FP2ThetaMean","FP2AlphaMean","FP2BetaMean","FP2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF7Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F7ThetaMean","F7AlphaMean","F7BetaMean","F7DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF3Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F3ThetaMean","F3AlphaMean","F3BetaMean","F3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVFzStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FzThetaMean","FzAlphaMean","FzBetaMean","FzDeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF4Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F4ThetaMean","F4AlphaMean","F4BetaMean","F4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF8Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F8ThetaMean","F8AlphaMean","F8BetaMean","F8DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT3Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T3ThetaMean","T3AlphaMean","T3BetaMean","T3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVC3Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","C3ThetaMean","C3AlphaMean","C3BetaMean","C3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVCzStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","CzThetaMean","CzAlphaMean","CzBetaMean","CzDeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVC4Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","C4ThetaMean","C4AlphaMean","C4BetaMean","C4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT4Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T4ThetaMean","T4AlphaMean","T4BetaMean","T4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT5Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T5ThetaMean","T5AlphaMean","T5BetaMean","T5DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVP3Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","P3ThetaMean","P3AlphaMean","P3BetaMean","P3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVP4Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","P4ThetaMean","P4AlphaMean","P4BetaMean","P4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT6Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T6ThetaMean","T6AlphaMean","T6BetaMean","T6DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVO1Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","O1ThetaMean","O1AlphaMean","O1BetaMean","O1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVO2Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","O2ThetaMean","O2AlphaMean","O2BetaMean","O2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRV1Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","A1ThetaMean","A1AlphaMean","A1BetaMean","A1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVA2Story.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","A2ThetaMean","A2AlphaMean","A2BetaMean","A2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVPZStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","PZThetaMean","PZAlphaMean","PZBetaMean","PZDeltaMean")])
  dev.off()
  
  #alpha,theta,beta,delta
  pdf(file = "pairs_AlphaPrePluaFrontalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1AlphaMean","FP2AlphaMean","F7AlphaMean","F3AlphaMean","FzAlphaMean","F4AlphaMean","F8AlphaMean")])
  dev.off()
  #conclusion alpha is highly correlated in frontal
  pdf(file = "pairs_AlphaCentralTemporalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3AlphaMean","T4AlphaMean","T5AlphaMean","T6AlphaMean","CzAlphaMean","C3AlphaMean","C4AlphaMean")])
  dev.off()
  pdf(file = "pairs_AlphaParietalOccipitalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3AlphaMean","P4AlphaMean","PZAlphaMean","O1AlphaMean","O2AlphaMean")])
  dev.off()
  
  #Beta
  pdf(file = "pairs_BetaPrePluaFrontalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1BetaMean","FP2BetaMean","F7BetaMean","F3BetaMean","FzBetaMean","F4BetaMean","F8BetaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_BetaCentralTemporalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3BetaMean","T4BetaMean","T5BetaMean","T6BetaMean","CzBetaMean","C3BetaMean","C4BetaMean")])
  dev.off()
  pdf(file = "pairs_BetaParietalOccipitalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3BetaMean","P4BetaMean","PZBetaMean","O1BetaMean","O2BetaMean")])
  dev.off()
  
  #Theta
  pdf(file = "pairs_ThetaPrePluaFrontalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1ThetaMean","FP2ThetaMean","F7ThetaMean","F3ThetaMean","FzThetaMean","F4ThetaMean","F8ThetaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_ThetaCentralTemporalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3ThetaMean","T4ThetaMean","T5ThetaMean","T6ThetaMean","CzThetaMean","C3ThetaMean","C4ThetaMean")])
  dev.off()
  pdf(file = "pairs_ThetaParietalOccipitalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3ThetaMean","P4ThetaMean","PZThetaMean","O1ThetaMean","O2ThetaMean")])
  dev.off()
  
  #Delta
  pdf(file = "pairs_DeltaPrePluaFrontalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1DeltaMean","FP2DeltaMean","F7DeltaMean","F3DeltaMean","FzDeltaMean","F4DeltaMean","F8DeltaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_DeltaCentralTemporalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3DeltaMean","T4DeltaMean","T5DeltaMean","T6DeltaMean","CzDeltaMean","C3DeltaMean","C4DeltaMean")])
  dev.off()
  pdf(file = "pairs_DeltaParietalOccipitalStory.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3DeltaMean","P4DeltaMean","PZDeltaMean","O1DeltaMean","O2DeltaMean")])
  dev.off()
  #attention to cz and pZ
  
  #meditation
  dfslted=df[which(df[,'time']>600),]
  dfslted=dfslted[which(dfslted[,'time']<900),]
  library(GGally)
  #ggpairs(dfslted,columns=c("HR", "SC", "HRV", "Resp","ST","FP1ThetaMean"))
  pdf(file = "pairs_betweenBioMAndFP1ThetaMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HR", "SC", "HRV", "Resp","ST","FP1ThetaMean")])
  dev.off()
  pdf(file = "pairs_HRVFP1Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FP1ThetaMean","FP1AlphaMean","FP1BetaMean","FP1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVFP2Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FP2ThetaMean","FP2AlphaMean","FP2BetaMean","FP2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF7Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F7ThetaMean","F7AlphaMean","F7BetaMean","F7DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF3Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F3ThetaMean","F3AlphaMean","F3BetaMean","F3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVFzMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","FzThetaMean","FzAlphaMean","FzBetaMean","FzDeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF4Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F4ThetaMean","F4AlphaMean","F4BetaMean","F4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVF8Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","F8ThetaMean","F8AlphaMean","F8BetaMean","F8DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT3Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T3ThetaMean","T3AlphaMean","T3BetaMean","T3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVC3Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","C3ThetaMean","C3AlphaMean","C3BetaMean","C3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVCzMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","CzThetaMean","CzAlphaMean","CzBetaMean","CzDeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVC4Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","C4ThetaMean","C4AlphaMean","C4BetaMean","C4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT4Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T4ThetaMean","T4AlphaMean","T4BetaMean","T4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT5Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T5ThetaMean","T5AlphaMean","T5BetaMean","T5DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVP3Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","P3ThetaMean","P3AlphaMean","P3BetaMean","P3DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVP4Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","P4ThetaMean","P4AlphaMean","P4BetaMean","P4DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVT6Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","T6ThetaMean","T6AlphaMean","T6BetaMean","T6DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVO1Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","O1ThetaMean","O1AlphaMean","O1BetaMean","O1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVO2Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","O2ThetaMean","O2AlphaMean","O2BetaMean","O2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRV1Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","A1ThetaMean","A1AlphaMean","A1BetaMean","A1DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVA2Mdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","A2ThetaMean","A2AlphaMean","A2BetaMean","A2DeltaMean")])
  dev.off()
  pdf(file = "pairs_HRVPZMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("HRV","PZThetaMean","PZAlphaMean","PZBetaMean","PZDeltaMean")])
  dev.off()
  
  #alpha,theta,beta,delta
  pdf(file = "pairs_AlphaPrePluaFrontalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1AlphaMean","FP2AlphaMean","F7AlphaMean","F3AlphaMean","FzAlphaMean","F4AlphaMean","F8AlphaMean")])
  dev.off()
  #conclusion alpha is highly correlated in frontal
  pdf(file = "pairs_AlphaCentralTemporalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3AlphaMean","T4AlphaMean","T5AlphaMean","T6AlphaMean","CzAlphaMean","C3AlphaMean","C4AlphaMean")])
  dev.off()
  pdf(file = "pairs_AlphaParietalOccipitalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3AlphaMean","P4AlphaMean","PZAlphaMean","O1AlphaMean","O2AlphaMean")])
  dev.off()
  
  #Beta
  pdf(file = "pairs_BetaPrePluaFrontalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1BetaMean","FP2BetaMean","F7BetaMean","F3BetaMean","FzBetaMean","F4BetaMean","F8BetaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_BetaCentralTemporalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3BetaMean","T4BetaMean","T5BetaMean","T6BetaMean","CzBetaMean","C3BetaMean","C4BetaMean")])
  dev.off()
  pdf(file = "pairs_BetaParietalOccipitalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3BetaMean","P4BetaMean","PZBetaMean","O1BetaMean","O2BetaMean")])
  dev.off()
  
  #Theta
  pdf(file = "pairs_ThetaPrePluaFrontalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1ThetaMean","FP2ThetaMean","F7ThetaMean","F3ThetaMean","FzThetaMean","F4ThetaMean","F8ThetaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_ThetaCentralTemporalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3ThetaMean","T4ThetaMean","T5ThetaMean","T6ThetaMean","CzThetaMean","C3ThetaMean","C4ThetaMean")])
  dev.off()
  pdf(file = "pairs_ThetaParietalOccipitalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3ThetaMean","P4ThetaMean","PZThetaMean","O1ThetaMean","O2ThetaMean")])
  dev.off()
  
  #Delta
  pdf(file = "pairs_DeltaPrePluaFrontalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("FP1DeltaMean","FP2DeltaMean","F7DeltaMean","F3DeltaMean","FzDeltaMean","F4DeltaMean","F8DeltaMean")])
  dev.off()
  #conclusion beta
  pdf(file = "pairs_DeltaCentralTemporalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("T3DeltaMean","T4DeltaMean","T5DeltaMean","T6DeltaMean","CzDeltaMean","C3DeltaMean","C4DeltaMean")])
  dev.off()
  pdf(file = "pairs_DeltaParietalOccipitalMdt.pdf", width = 9, height = 9, pointsize = 10)
  pairs(dfslted[c("P3DeltaMean","P4DeltaMean","PZDeltaMean","O1DeltaMean","O2DeltaMean")])
  dev.off()
  #attention to cz and pZ
  
  #representation of one signal in whole experience
  pdf(file = "HRAgainstTime.pdf", width = 9, height = 9, pointsize = 10)
  plot(df$time,df$HR,type="l",ylim=c(60,105),main="Heart Rate according to time")

  library(pracma)
  Y=movavg(df$HR,20,type="s")
  lines(Y,col="red")

  abline(v=450, col="Deeppink",lty=2)
  legend("topright", legend=c("moving average window=20 data points", "original data","transition of phase"),
         col=c("red", "black","Deeppink"), lty=c(1,1,2), cex=0.8)
  dev.off()
  
  #watching HRV
  pdf(file = "HRVAgainstTime.pdf", width = 9, height = 9, pointsize = 10)
  Y=movavg(df$HRV[3:length(df$HRV)],20,type="s")
  plot(df$time[3:length(df$time)],df$HRV[3:length(df$HRV)],type="l",ylab="HRV",xlab="time", ylim=c(100,500), main="Heart Rate variability according to time")
  abline(v=450, col="Deeppink",lty=2)
  legend("right", legend=c("transition of phase","HRV raw data"),
         col=c("Deeppink","black"), lty=c(2,1), cex=0.8)
  dev.off()
  
  #respiration
  pdf(file = "RespAgainstTime.pdf", width = 9, height = 9, pointsize = 10)
  plot(df$time,df$Resp,type="l",ylim=c(0,40),ylab="respiration(BPM)",xlab="time",main="respiration(BPM) according to time")
  abline(v=450, col="Deeppink",lty=2)
  legend("right", legend=c("transition of phase","respiration raw data"),
         col=c("Deeppink","black"), lty=c(2,1), cex=0.8)
  dev.off()
  
  #skin conductance
  pdf(file = "SCAgainstTime.pdf", width = 9, height = 9, pointsize = 10)
  plot(df$time,df$SC,type="l",ylim=c(1.4,2.4),xlab="time",ylab="skin conductance (micro Siemens)",main="Skin conductance according to time")
  abline(v=450, col="Deeppink",lty=2)
  legend("topright", legend=c("transition of phase","skin conductance raw data"),
         col=c("Deeppink","black"), lty=c(2,1), cex=0.8)
  dev.off()
  
  #skin temp
  pdf(file = "STAgainstTime.pdf", width = 9, height = 9, pointsize = 10)
  plot(df$time,df$ST,type="l",ylim=c(18.4,19),ylab="skin temperature",xlab="time",main="Skin temperature according to time")
  abline(v=450, col="Deeppink",lty=2)
  legend("topright", legend=c("transition of phase","skin temperature raw data"),
         col=c("Deeppink","black"), lty=c(2,1), cex=0.8)
  dev.off()
  
  #define universal ybounds func
  ybounds <- function(y){  # y is the response variable in the dataframe
    bounds = quantile(y, probs=c(0.05, 0.95), type=3, names=FALSE)
    return(bounds + c(-1,1) * 0.2 * (bounds[2]-bounds[1]) )
  }
  #select eeg signals
  df_eeg=subset(df,select=-c(time,HR,HRV,Resp,ST,SC,MediOrStory))
  for (col in 1:(ncol(df_eeg))){
    pdf(file = paste(colnames(df_eeg[col]),"average power against time.pdf"), width = 9, height = 9, pointsize = 10)
    par(mfrow=c(1,2))
    plot(df$time,df_eeg[,col],type="l",ylim=ybounds(df_eeg[,col]),ylab= paste(colnames(df_eeg[col]),"average power(micro volt)"),main=paste(colnames(df_eeg[col])," power against time(raw data)"))
    Y=movavg(df_eeg[,col],20,type="s")
    plot(df$time,Y,type="l",col="red",xlab="time",ylab= paste(colnames(df_eeg[col]),"average power(micro volt)"),ylim=ybounds(df_eeg[,col]),main=paste(colnames(df_eeg[col])," power according to time"))
    abline(v=450, col="Deeppink",lty=2)
    legend("topright", legend=c("transition of phase","moving average line"),
           col=c("Deeppink","red"), lty=c(2,1), cex=0.8)
    dev.off()
  }
  
  pval_name=paste("pval of ",subject_name)
  pValTable=data.frame("Model"="ini",pval_name=0)
  pValTable$Model=as.character(pValTable$Model)
  df_bio=subset(df,select=c(HR,HRV,Resp,ST,SC))
  library(car)
  par(mfrow=c(1,1))
  for (col in 1:(ncol(df_bio))){
    for(col1 in col:(ncol(df_bio))){
      if(col!=col1){
        #print(col)
        #print(col1)
        pdf(file = paste(colnames(df_bio[col]),"correlated with",colnames(df_bio[col1]),".pdf"), width = 9, height = 9, pointsize = 10)
        plot(df_bio[,col],df_bio[,col1],ylab=colnames(df_bio[col1]), xlim=ybounds(df_bio[,col]),ylim=ybounds(df_bio[,col1]),xlab=colnames(df_bio[col]),col=c("red","blue")[df$MediOrStory])
        
        df_bio$MediOrStory=df$MediOrStory
        dfslted=df_bio[which(df_bio[,'MediOrStory']==1),]
        dfslted=dfslted[which(dfslted[,col]<ybounds(dfslted[,col])[2]),]
        dfslted=dfslted[which(dfslted[,col]>ybounds(dfslted[,col])[1]),]
        dfslted=dfslted[which(dfslted[,col1]<ybounds(dfslted[,col1])[2]),]
        dfslted=dfslted[which(dfslted[,col1]>ybounds(dfslted[,col1])[1]),]
        reg_Medi=lm(dfslted[,col1]~dfslted[,col],data = dfslted)
        
        f <- summary(reg_Medi)$fstatistic
        p <- pf(f[1],f[2],f[3],lower.tail=F)
        attributes(p) <- NULL
        #nomination is"yX+Mdt or Story" which signify y=ax+b
        pValTable=rbind(pValTable,list(paste(colnames(df_bio[col1]),colnames(df_bio[col]),"Mdt"),as.numeric(p)))
        
        abline(reg_Medi,col="goldenrod")
        dfslted=df_bio[which(df_bio[,'MediOrStory']==0),]
        dfslted=dfslted[which(dfslted[,col]<ybounds(dfslted[,col])[2]),]
        dfslted=dfslted[which(dfslted[,col]>ybounds(dfslted[,col])[1]),]
        dfslted=dfslted[which(dfslted[,col1]<ybounds(dfslted[,col1])[2]),]
        dfslted=dfslted[which(dfslted[,col1]>ybounds(dfslted[,col1])[1]),]
        reg_Story=lm(dfslted[,col1]~dfslted[,col],data = dfslted)
        
        f <- summary(reg_Story)$fstatistic
        p <- pf(f[1],f[2],f[3],lower.tail=F)
        attributes(p) <- NULL
        pValTable=rbind(pValTable,list(paste(colnames(df_bio[col1]),colnames(df_bio[col]),"Story"),as.numeric(p)))
        
        abline(reg_Story,col="darkseagreen")
        legend( x="topright", 
                legend=c("scatter plot of story phase","scatter plot of meditation","regression during story phase","regression during meditation"),
                col=c("red","blue","darkseagreen","goldenrod"), lwd=1, 
                pch=c(16,16) )
        df_bio=subset(df_bio,select=-MediOrStory)
        dev.off()
      }
    }}
  
  for (col in 1:(ncol(df_eeg))){
    pdf(file = paste(colnames(df_eeg[col]),"correlated with HRV",".pdf"), width = 9, height = 9, pointsize = 10)
    df_eeg$HRV=df$HRV 
    df_eeg$MediOrStory=df$MediOrStory
    plot(df_eeg[,col],df_eeg[,'HRV'],ylab="HRV", xlim=ybounds(df_eeg[,col]),ylim=ybounds(df_eeg[,'HRV']),xlab=colnames(df_eeg[col]),col=c("red","blue")[df$MediOrStory])
    #plot(df_eeg[,col],df_eeg[,'HRV'],ylab="HRV",xlab=colnames(df_eeg[col]),col=c("red","blue")[df_eeg$MediOrStory])
    
    
    
    dfslted=df_eeg[which(df_eeg[,'MediOrStory']==1),]
    dfslted=dfslted[which(dfslted[,col]<ybounds(dfslted[,col])[2]),]
    dfslted=dfslted[which(dfslted[,col]>ybounds(dfslted[,col])[1]),]
    dfslted=dfslted[which(dfslted[,'HRV']<ybounds(dfslted[,'HRV'])[2]),]
    dfslted=dfslted[which(dfslted[,'HRV']>ybounds(dfslted[,'HRV'])[1]),]
    reg_Medi=lm(dfslted[,'HRV']~dfslted[,col],data = dfslted)
    
    f <- summary(reg_Medi)$fstatistic
    p <- pf(f[1],f[2],f[3],lower.tail=F)
    attributes(p) <- NULL
    #nomination is"yX+Mdt or Story" which signify y=ax+b
    pValTable=rbind(pValTable,list(paste("HRV",colnames(df_eeg[col]),"Mdt"),as.numeric(p)))
    
    abline(reg_Medi,col="goldenrod")
    dfslted=df_eeg[which(df_eeg[,'MediOrStory']==0),]
    dfslted=dfslted[which(dfslted[,col]<ybounds(dfslted[,col])[2]),]
    dfslted=dfslted[which(dfslted[,col]>ybounds(dfslted[,col])[1]),]
    dfslted=dfslted[which(dfslted[,'HRV']<ybounds(dfslted[,'HRV'])[2]),]
    dfslted=dfslted[which(dfslted[,'HRV']>ybounds(dfslted[,'HRV'])[1]),]
    reg_Story=lm(dfslted[,'HRV']~dfslted[,col],data = dfslted)
    
    f <- summary(reg_Story)$fstatistic
    p <- pf(f[1],f[2],f[3],lower.tail=F)
    attributes(p) <- NULL
    pValTable=rbind(pValTable,list(paste("HRV",colnames(df_eeg[col]),"Story"),as.numeric(p)))
    
    abline(reg_Story,col="darkseagreen")
    
    #abline(reg_Story,col="black")
    legend( x="topright", 
            legend=c("scatter plot of story phase","scatter plot of meditation","regression during story phase","regression during meditation"),
            col=c("red","blue","darkseagreen","goldenrod"), lwd=1, 
            pch=c(16,16) )
    df_eeg=subset(df_eeg,select=-c(MediOrStory,HRV))
    dev.off()
  }
  export_pVal_name=paste(subject_name," p_val.csv")
  #!!! verify the path!!!
  setwd("E:/important file/CENTRALE/BCI ET EEG/Rprocess/data/hugues_auto")
  write.csv(pValTable, file = export_pVal_name,row.names = FALSE)
  return(pValTable)
}

#graph_generation(HU,"Hugues")
